name       : xapian-core
version    : 1.4.5
release    : 3
source     :
    - https://oligarchy.co.uk/xapian/1.4.5/xapian-core-1.4.5.tar.xz : 85b5f952de9df925fd13e00f6e82484162fd506d38745613a50b0a2064c6b02b
license    : GPL-2.0
component  : programming
summary    : Open Source Search Engine Library
description: |
    Open Source Search Engine Library
builddeps  :
    - pkgconfig(uuid)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
