name       : xapian-core
version    : 1.4.11
release    : 7
source     :
    - https://oligarchy.co.uk/xapian/1.4.11/xapian-core-1.4.11.tar.xz : 9f16b2f3e2351a24034d7636f73566ab74c3f0729e9e0492934e956b25c5bc07
license    : GPL-2.0-or-later
component  : programming
summary    : Open Source Search Engine Library
description: |
    Open Source Search Engine Library
builddeps  :
    - pkgconfig(uuid)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
