name       : xapian-core
version    : 1.4.6
release    : 4
source     :
    - https://oligarchy.co.uk/xapian/1.4.6/xapian-core-1.4.6.tar.xz : 1e0ef1c1d3e2119874d545b7edbb60e6e17d7d18fb802eb890d9ef7bb0bbd898
license    : GPL-2.0-or-later
component  : programming
summary    : Open Source Search Engine Library
description: |
    Open Source Search Engine Library
builddeps  :
    - pkgconfig(uuid)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
