name       : xapian-core
version    : 1.4.19
release    : 8
source     :
    - https://oligarchy.co.uk/xapian/1.4.19/xapian-core-1.4.19.tar.xz : 1fca48fca6cc3526cc4ba93dd194fe9c1326857b78edcfb37e68d086d714a9c3
homepage   : https://xapian.org/
license    : GPL-2.0-or-later
component  : programming
summary    : Open Source Search Engine Library
description: |
    Xapian is an Open Source Search Engine Library. It's written in C++, with bindings to allow use from Perl, Python 2, Python 3, PHP 5, PHP 7, Java, Tcl, C#, Ruby, Lua, Erlang, Node.js and R. Xapian is a highly adaptable toolkit which allows developers to easily add advanced indexing and search facilities to their own applications. It has built-in support for several families of weighting models and also supports a rich set of boolean query operators.
builddeps  :
    - pkgconfig(uuid)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
