name       : xapian-core
version    : 1.4.0
release    : 1
source     :
    - http://oligarchy.co.uk/xapian/1.4.0/xapian-core-1.4.0.tar.xz : 10584f57112aa5e9c0e8a89e251aecbf7c582097638bfee79c1fe39a8b6a6477
license    : GPL-2.0
component  : programming
summary    : Open Source Search Engine Library
description: |
    Open Source Search Engine Library
builddeps  :
    - pkgconfig(uuid)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
