name       : xapian-core
version    : 1.4.10
release    : 5
source     :
    - https://oligarchy.co.uk/xapian/1.4.10/xapian-core-1.4.10.tar.xz : 68669327e08544ac88fe3473745dbcae4e8e98d5060b436c4d566f1f78709bb8
license    : GPL-2.0-or-later
component  : programming
summary    : Open Source Search Engine Library
description: |
    Open Source Search Engine Library
builddeps  :
    - pkgconfig(uuid)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
